# versionは、3系
version: "3"
# Serviceを設定する
services:
  # Service名は、自由に決めていい
  simple-news:
    # DockerfileまでのPath
    build: .
    # ホストマシン:コンテナ => ファイルを共有するための設定
    volumes:
      - ./app:/usr/src/app
      # - ./app:/usr/src/app/node_modules
    # ホストマシンPort番号:コンテナのPost番号
    ports:
      # Next.js との ポートフォワード
      - 3008:3000
      # StoryBook との ポートフォワード
      - 6006:6006
    # CLI画面の操作をできるようにする
    tty: true